services:
  api:
    image: hawkinsr/helloapp:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - target: 80
        published: 8080
        protocol: tcp
      - target: 443
        published: 4443
        protocol: tcp
  ui:
    image: hawkinsr/demoapp:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
    - target: 80
      published: 3000
      protocol: tcp
    - target: 443
      published: 3443
      protocol: tcp